ROLE_USER = 'user'
ROLE_DEPT_ADMIN = 'dept_admin'
ROLE_SUPER_ADMIN = 'super_admin'

ROLE_LEVELS = {
    ROLE_USER: 1,
    ROLE_DEPT_ADMIN: 2,
    ROLE_SUPER_ADMIN: 3,
}

VALID_ROLES = {ROLE_USER, ROLE_DEPT_ADMIN, ROLE_SUPER_ADMIN}
